json.access_token @user.access_token
json.facebook_id @user.facebook_id 
json.facebook_img @user.facebook_img 
json.facebook_token @user.facebook_token
json.id @user.id 
json.name @user.name
json.university_id @user.university_id 
json.created_at @user.created_at.to_i
json.updated_at @user.updated_at.to_i